### ISSUE TITLE
Is the part of code about pose extraction included in here?"

### ISSUE THREAD

**Issue by hoper11** [NomiMalik0207/PedSynth-and-PedGNN-for-Pedestrian-Intention-Prediction#1]

**Comment by NomiMalik0207** [comment]
Hi Hoper,
Thanks for your question.
I did not include pose extraction code here in the repository, we use alphapose for pose extraction. for your ease, if you want to extract the pose easily use the link below
https://debuggercafe.com/real-time-pose-estimation-using-alphapose-pytorch-and-deep-learning/
from this link, you can install and use Alphapose for inference smoothly.
Please let me know if you require any other information.

**Comment by SugarMuzi** [comment]
> Hi Hoper, Thanks for your question. I did not include pose extraction code here in the repository, we use alphapose for pose extraction. for your ease, if you want to extract the pose easily use the link below https://debuggercafe.com/real-time-pose-estimation-using-alphapose-pytorch-and-deep-learning/ from this link, you can install and use Alphapose for inference smoothly. Please let me know if you require any other information.

hello,thanks for your work! i have a question:I want to know what the cs described in the picture below means
![image](https://github.com/NomiMalik0207/PedSynth-and-PedGNN-for-Pedestrian-Intention-Prediction/assets/125560403/cade30c4-353e-488b-9711-c0111c906973)

**Comment by NomiMalik0207** [comment]
Hi,
The cs is the confidence score of each body part. Please let me know if you required any further assistance.

**Comment by SugarMuzi** [comment]
> Hi, The cs is the confidence score of each body part. Please let me know if you required any further assistance.

thanks for your answer, i have no more problem.
